# Project Euler problem 2
# Solution by Charlotte Aten (caten2@u.rochester.edu)
# Problem statement:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

class Fibonacci():
    """The infinite sequence beginning with 1,2 where each subsequent term is obtained by
    adding the previous two terms in the sequence."""

    # Create a generator which corresponds to the infinite Fibonacci sequence.
    def Sequence(self):
        i = 1
        j = 1
        while True:
            i, j = j, i+j
            yield i

    # Generate elements from the Fibonacci sequence until the desired number have been produced.
    def FirstNTerms(self, number):
        count = 0
        for i in self.Sequence():
            if count >= number:
                break
            else:
                yield(i)
                count = count + 1

    # Give a list of the numbers yielded by the FistNTerms generator.
    def ListFirstNTerms(self, number):
        return list(self.FirstNTerms(number))

    # Generate all terms of the Fibonacci sequence below a specified value.
    def SequencceUpTo(self, maximum):
        for i in self.Sequence():
            if i < maximum:
                yield i
            else:
                break

    # Give a list of the numbers yielded by the SequenceUpTo generator.
    def ListSequenceUpTo(self, maximum):
        return list(self.SequencceUpTo(maximum))

    # Use the SequenceUpTo generator to check the sequence below a specified value.
    # Add the even terms to the running total, throw out the odd terms.
    def SumEvensUpTo(self, maximum):
        total = 0
        for i in self.SequencceUpTo(maximum):
            # Recall that a number i is even iff i is congruent to 0 modulo 2.
            if i % 2 == 0:
                total = total + i
        return total

print("Create an object for the Fibonacci sequence.")
F = Fibonacci()

print("List the first 10 terms of the Fibonacci sequence.")
print(F.ListFirstNTerms(10))
print("")

print("List the sum of even terms up to 100.")
print(F.SumEvensUpTo(100))
print("")

print("List the sum of even terms up to 4 million.")
print(F.SumEvensUpTo(4000000))